### PR TITLE
SWAP-1201 CI/CD Improvements

### PR DESCRIPTION
**Pull request by peter-asztalos**
## Description

This PR updates the Github action and Docker configurations to improve the overall speed, size of the images and makes action files consistent.

## Motivation and Context

The previous solution didn't use any caching.

## Fixes

https://jira.esss.lu.se/browse/SWAP-1201

## Changes

- save intermediate layers after each build and use them if there were no changes
- docker ignore updated to provide a better caching experience 
- use multi-stage builds to reduce image size (~360->~150mb)
- package.json updated to use only proper dependencies in each environment
- e2e test related configurations

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

### CODE REVIEW

**Review by jekabs-karklins — APPROVED** [review]

**Comment by jekabs-karklins** [comment]
Did you look into how to auto-deploy deploy to the user office test? 
I remember we wanted to use GitLab runners for this, but I believe we need to invoke that from GitHub's actions.

**Review by jekabs-karklins — APPROVED** [review]

**Comment by peter-asztalos** [comment]
User office test? Do you mean auto-deploy to the testing environment? I haven't yet, but I can look into it.

**Comment by jekabs-karklins** [comment]
> User office test? Do you mean auto-deploy to the testing environment? I haven't yet, but I can look into it.

Yes, the auto-deploy. When we talked with @bolmsten it sounded like it has a priority. 
But it also sounds like a separate task. We should probably create a task for it and prioritize accordingly.

**Comment by peter-asztalos** [comment]
> Yes, the auto-deploy. When we talked with @bolmsten it sounded like it has a priority.
> But it also sounds like a separate task. We should probably create a task for it and prioritize accordingly.

I see, I'll look into it, so the goal is to deploy to testing on merge to develop branch?

**Review by martin-trajanovski — APPROVED** [review]

**Pull request merged**
